name:                amayadori
version:             0.1.0
github:              "cormojs/amayadori"
license:             BSD3
author:              "Cormo JS"
maintainer:          "cormorant2+github@gmail.com"
copyright:           "2019 Cormo JS"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cormojs/amayadori#readme>

dependencies:
- base >= 4.7 && < 5
- serverless-haskell
- aeson

library:
  source-dirs: src

executables:
  amayadori-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amayadori

tests:
  amayadori-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amayadori
